name: Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: c-hive/gha-npm-cache@v1
      - run: npm i --ignore-scripts
      - run: npm run lint
